### ISSUE TITLE
Flare core dumps under Ubuntu 17.10

### ISSUE THREAD

**Issue by tvleavitt** [flareteam/flare-engine#1618] opened 2018-03-17 11:39 UTC
Built Flare 1.0.06 from source as I did under OS X in an Ubuntu 17.10 virtual machine, with all sdl  dependences installed from packages. Appeared to build successfully. Created symlinks between flare-engine and flare-game Started it via "./flare". Enabled full screen mode, resolution set to 1920x1080. Enabled standard three mods. Game crashed as it attempted to load first map, right after clicking "Create" on the character screen. I hear the music begin to play, then boom... CTD.

Last output to console before core dump:

INFO: Map: Loading map 'maps/arrival.txt'
Segmentation fault (core dumped)

Don't see a core dump anywhere, however. Playing around with video settings, using sdl and not hardware render, unchecking all options, etc., same behavior every time. Suggestions for how to troubleshoot this welcome.

**Comment by dorkster** [comment] 2018-03-17 12:49
To debug Flare:

```
cmake . -DCMAKE_BUILD_TYPE=Debug
make
gdb ./flare
```

When the game crashes, enter `backtrace` and post the output of that here.

**Comment by tvleavitt** [comment] 2018-03-19 09:03
I've maybe used gdb twice in my life; I'm a sysadmin, when I code, it's in Perl or PHP, not C. Help me out a bit here with what I should do to generate some useful output?

**Comment by tvleavitt** [comment] 2018-03-19 09:24
Just using "r", this is what I get to the console:

INFO: Map: Loading map 'maps/arrival.txt'

Thread 1 "flare" received signal SIGSEGV, Segmentation fault.
0x00007ffff7aeec88 in ?? () from /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0

**Comment by dorkster** [comment] 2018-03-19 16:04
Ah, looks like  Ubuntu 17.10 ships with SDL 2.0.6. That makes this appear to be a duplicate of https://github.com/clintbellanger/flare-engine/issues/1516.

Our prebuilt Linux version ships with SDL 2.0.4, so this doesn't surface there. And it appears that 18.04 will be shipping with SDL 2.0.8, so it should be fixed there.

**Comment by tvleavitt** [comment] 2018-03-19 19:54
O.K. I'll look at how to upgrade this. Thanks.

**Comment by tvleavitt** [comment] 2018-03-20 02:51
Here's the Ubuntu bug report. It is unclear whether they're going to make the effort of back porting 2.0.7 to "artful".

https://bugs.launchpad.net/ubuntu/+source/libsdl2/+bug/1722060

**Closed** 2021-10-10 02:03 UTC
Labels: bug
