### ISSUE TITLE
Engine crash issues on missing files

### ISSUE THREAD

**Issue by clintbellanger** [flareteam/flare-engine#1458] opened 2016-06-02 18:46 UTC
I'm setting up the basics for a Wandercall core mod and chapter of content. I'm copying configurations over from fantasycore and alpha_demo.

I'm getting a crash when GameStatePlay is starting, I haven't yet figured out what is missing this time.

Here are the WIP mods currently causing the crash, wandercore and wandercall_ch1. Grab these for troubleshooting.

https://github.com/clintbellanger/wandercall-ch1/commit/4069582dec6406e4bedacaaf275b457d2aa81382

We may leave this issue open until I can reach an empty GameStatePlay without crashes happening.

**Comment by clintbellanger** [comment] 2016-06-02 18:59
I'm not worried (yet) about missing files that aren't required, but ones that are causing the engine to halt. 

Here's the current output, how far it gets into the gameplay inits before dying.

> INFO: No joysticks were found.
> INFO: Using Render Device: SDLSoftwareRenderDevice (software, SDL 2)
> ERROR: SoundManager: Couldn't load music file 'music/title_theme.ogg': Couldn't open ''
> ERROR: SoundManager: Couldn't load music file 'music/title_theme.ogg': Couldn't open ''
> ERROR: FileParser: items/items.txt: Could not open text file: No such file or directory!
> ERROR: FileParser: items/types.txt: Could not open text file: No such file or directory!
> ERROR: FileParser: items/sets.txt: Could not open text file: No such file or directory!
> ERROR: FileParser: items/qualities.txt: Could not open text file: No such file or directory!
> INFO: ItemManager: No items were found.
> INFO: ItemManager: No item sets were found.
> ERROR: SoundManager: Couldn't load music file 'music/title_theme.ogg': Couldn't open ''
> ERROR: SoundManager: Couldn't load music file 'music/title_theme.ogg': Couldn't open ''
> ERROR: FileParser: powers/effects.txt: Could not open text file: No such file or directory!
> ERROR: FileParser: powers/powers.txt: Could not open text file: No such file or directory!
>

**Comment by clintbellanger** [comment] 2016-06-02 19:03
gdb says this.

> Program received signal SIGSEGV, Segmentation fault.
> 0x004a9325 in StatBlock::recalc() ()

**Comment by clintbellanger** [comment] 2016-06-02 19:29
Ok, this issue was the xp_table.txt contents being incorrect. I copied the correct values over from the updated alpha_demo.

So if xp table doesn't contain valid content, it seems to cause an engine crash.

**Comment by dorkster** [comment] 2016-06-02 21:28
I suspect the problem is [here](https://github.com/clintbellanger/flare-engine/blob/master/src/StatBlock.cpp#L510). Could you provide a copy of the xp_table.txt you used?

Also, it would be helpful to see the backtrace for that crash. If you're building with CMake, use this in the repo root:

```
cmake . -DCMAKE_BUILD_TYPE=Debug
make
```

**Comment by clintbellanger** [comment] 2016-06-03 02:14
This is the xp table file: https://github.com/clintbellanger/wandercall-ch1/blob/master/wandercall_ch1/engine/xp_table.txt

I can provide the backtrace tomorrow.

**Comment by dorkster** [comment] 2016-06-03 03:29
Ah, that's the old syntax for the XP table ([current looks like this](https://github.com/clintbellanger/flare-game/blob/master/mods/alpha_demo/engine/xp_table.txt)), so definitely malformed data.

The game's not crashing at the XP table stuff for me, so I doubt that has anything to do with this. So bugs are elsewhere.

**Comment by dorkster** [comment] 2016-06-03 05:15
Okay, there should now be no crash with the current Wandercall mod.

**Comment by clintbellanger** [comment] 2016-06-30 00:43
New crash issue. To reproduce:
Use the latest Wandercall mod checkin: https://github.com/clintbellanger/wandercall-ch1/commit/edf42ef8040572d68a4c4ceacc3932f716f2de8f

Start a new character.
Open the Power menu.
Put the Swing power on the Action Bar.
That's where it crashes for me.
Or, if I use a safe file with Swing already on the action bar, it crashes on game load.

The crash reportedly happens in the function void GameStatePlay::updateActionBar(index).

I've been trying to add config files only as I need them, but it's not apparent here what I'm missing.

**Comment by dorkster** [comment] 2016-06-30 01:12
Fixed the crash [here](https://github.com/clintbellanger/flare-engine/commit/9c55b6a75d6f45eab0988503c037dc8c2c650c96).

**Comment by clintbellanger** [comment] 2016-06-30 01:21
Thanks!

**Comment by clintbellanger** [comment] 2017-05-16 19:21
I have another crash related to Wandercall and config files.

I'm messing with Inventory menu configuratoin. The current master of Wandercall should run ok. But uncomment this line:

https://github.com/clintbellanger/wandercall-ch1/blob/master/wandercore/menus/inventory.txt#L14

And the game will crash around when it's entering gameplay (after load/new). For some reason those equipment slots are not being set.

Most likely there was some new or changed config related to this and I didn't pick it up in my WIP config data, which is forked from flare-game a few months ago and updated piecemeal.

**Comment by dorkster** [comment] 2017-05-16 20:55
Okay, that should be fixed now. It's because there were no items defined. Now there will be an item with an ID of 1. Where it doesn't have a name, it can't be added to your inventory via the dev console, but it will show up as "Unknown Item" if you add it by editing your save file.

**Closed** 2021-10-10 02:12 UTC
Labels: bug
