### ISSUE TITLE
Optional save game button

### ISSUE THREAD

**Issue by m7600** [flareteam/flare-engine#1736] opened 2019-10-13 02:38 UTC
Hi,

Sorry if this has been discussed before (I'm sure it has), but I couldn't find anything posted on the subject.
I would like to contribute a simple piece of code for an optional "save game" button. Would there be any interest in implementing this?

The button itself would be displayed at the "pause exit" menu, under the exit button. it would work as a new property that can be set to true or false in engine/misc.txt. If true, then the button would be visible and it would allow the player to save the game. If false, then it would not be visible, nor functional.
It would be optional because it would work in a way similar to save_onload, which alternates the labels "Save & Exit" and "Exit" on the exit button depending on true or false.

I know that I may be opening a can of worms with this. Not from a technical standpoint, but from a game design perspective. Don't get me wrong, if the idea is to use a similar save-load system to Diablo 1 and 2, then FLARE already does an excellent job at this. My question is, would an optional save game button alter that system? I don't think so. But this is also tied to the issue of "save scumming"... and that is the can of worms that I was referring to. On a personal level, I honestly believe that if players really want to cheat themselves, they're going to find the means to do it anyway. The lack of a hard-coded save button will not stop them, they will simply work their way around it (by editing the save game files, for example). 

So what would be the reasons against the implementation of this feature? I just thought it would be better to ask before I try to commit something. 

Cheers

**Comment by dorkster** [comment] 2019-10-13 03:24
I'm not opposed to the idea. Flare game designers could technically already achieve "save anywhere" behavior by making a Power that executes a `script` containing `save_game=true`. Of course, your proposal is a much cleaner, more standardized approach!

**Comment by m7600** [comment] 2019-10-13 12:09
Great! I'll get to work on it.

I actually did the script thing just like you described it on the mod I'm working on. The only difference is that I tied the power to an item. Don't know if you had a chance to check it out yet. If not, here's the link:

https://github.com/m7600/skeleton_quest

(I'm writting this from my cell phone, so please excuse me for not hyperlinking)

**Comment by m7600** [comment] 2019-10-13 21:02
Ok, here is what I have so far. I slightly modified four files: EngineSettings.h, EngineSettings.cpp, MenuConfig.cpp, and GamePlayState.cpp

I think I changed the first three succesfully. Here is what I modified/added:
EngineSettings.h
`		bool save_anywhere;`

EngineSettings.cpp
`	save_anywhere = false;`

MenuConfig.cpp
`	pause_continue_btn->setLabel((eset->misc.save_anywhere && enable_save) ? msg->get("Save & Continue") : msg->get("Continue"));`

I'm having trouble with GameStatePlay.cpp. I don't know where to put this:

`	if (eset->misc.save_anywhere)
		save_load->saveGame();`

I tried different options and they all "work"... but only in the undesired sense that the game is being permanently saved, at all times, no matter what the character does (there is a msg that says "Game saved" which never goes away...)

I know that I'm doing something wrong in GamePlayState.cpp, but for the life of me I can't figure out what. Some help please?

**Comment by dorkster** [comment] 2019-10-13 21:43
While it's possible to get the desired behavior in GameStatePlay.cpp, I think this particular feature can be accomplished by modifying MenuExit.cpp. Here's a diff that makes the "Continue" button save when clicked:
```
diff --git a/src/MenuExit.cpp b/src/MenuExit.cpp
index 6e15bb37..45227c47 100644
--- a/src/MenuExit.cpp
+++ b/src/MenuExit.cpp
@@ -27,6 +27,11 @@ FLARE.  If not, see http://www.gnu.org/licenses/
 #include "MenuExit.h"
 #include "SharedGameResources.h"
 
+#include "Avatar.h"
+#include "MapRenderer.h"
+#include "SaveLoad.h"
+#include "SharedResources.h"
+
 MenuExit::MenuExit()
 	: Menu()
 	, menu_config(new MenuConfig(!MenuConfig::IS_GAME_STATE))
@@ -55,6 +60,9 @@ void MenuExit::logic() {
 	if (menu_config->clicked_pause_continue) {
 		visible = false;
 		menu_config->clicked_pause_continue = false;
+
+		mapr->respawn_point = pc->stats.pos;
+		save_load->saveGame();
 	}
 	else if (menu_config->clicked_pause_exit) {
 		exitClicked = true;
```

In your code, you would wrap the logic relevant lines with `if (eset->misc.save_anywhere)`.

However, I don't think it's a good idea to change the behavior of the "Continue" button. I would rather add another button to the pause screen that is dedicated to saving (only visible if the engine flag is set). No pressure, but you're welcome to take that as a challenge.

**Comment by m7600** [comment] 2019-10-13 21:59
Of course! : D 
I love challenges like these. Like I said in the opengameart forums, I have been wanting to learn C++ for some time now, but nothing really motivated me to do so, until I saw the flare engine. Making the save game button is proving to be a humble but satisfactory learning experience for me, even if it did not get implemented.

As to making another button, I agree. That will probably require a WidgetLabel and WidgetButton in MenuConfig.h and MenuConfig.cpp. Maybe name them pause_save_lb and pause_save_btn?

Anyways, I'll try to come up with a proposal this week. Thanks for the help and direction!

**Comment by dorkster** [comment] 2019-10-13 22:01
>That will probably require a WidgetLabel and WidgetButton in MenuConfig.h and MenuConfig.cpp. Maybe name them pause_save_lb and pause_save_btn?

Yep! You're on the right track.

**Comment by m7600** [comment] 2019-10-14 03:43
Alright, here's what I have so far. It's functional, though very crude. Thank you so much for your patience, you must feel like you're talking to a bumbling illiterate! Anyways, here is what I did:

EngineSettings.h
`bool save_anywhere;`

EngineSettings.cpp
`save_anywhere = false;`

`// @ATTR save_anywhere|bool|Saves the game when using a button.`
`else if (infile.key == "save_anywhere")`
`save_anywhere = Parse::toBool(infile.val);`

MenuConfig.h
`	WidgetLabel                * pause_save_lb;`
'	WidgetButton               * pause_save_btn;'
`	bool clicked_pause_save;`

MenuConfig.cpp
`	, pause_save_lb(new WidgetLabel())`
`	, pause_save_btn(new WidgetButton(WidgetButton::DEFAULT_FILE))`

`	, clicked_pause_save(false)`
`
`	cfg_tabs[EXIT_TAB].setOptionWidgets(2, pause_save_lb, pause_save_btn, msg->get(""));`

```
	else if (cfg_tabs[EXIT_TAB].options[2].enabled && pause_save_btn->checkClickAt(mouse.x, mouse.y)) {
		clicked_pause_save = true;
	}
```

```
void MenuConfig::setPauseSaveText(bool enable_save) {
	pause_save_btn->setLabel((eset->misc.save_anywhere && enable_save) ? msg->get("Save Game") : msg->get("Nothing"));
}
```

MenuExit.cpp
```
#include "Avatar.h"
#include "MapRenderer.h"
#include "MenuConfig.h"
#include "MenuConfirm.h"
#include "MenuExit.h"
#include "SaveLoad.h"
#include "SharedGameResources.h"
#include "SharedResources.h"
```

```
	else if (menu_config->clicked_pause_save) {
		visible = false;
		menu_config->clicked_pause_save = false;

		mapr->respawn_point = pc->stats.pos;
		save_load->saveGame();
	}
```

In order to make this work, I had to delete pause_time_lb and pause_time_text. Obviously that's not acceptable, but I will try to incorporate them back.

**Comment by m7600** [comment] 2019-10-14 18:20
I made a new pull request, but please feel free to reject it. The save button works, but there is still some stuff to do to it. I just thought you might like to take a look at the files that I have modified so far to see if I'm going in the right direction with this. Thanks again.

**Comment by dorkster** [comment] 2019-10-14 19:03
Thanks for you work. In the process of investigating your PR and fixing the crash, I merged your commits and implemented the rest of the feature: 892e2bba042ace3eee5af33a8dfce54da2843a5b. Hopefully my commit makes it clear what needed to be changed. I've also credited you to the [release notes](https://github.com/flareteam/flare-engine/commit/0a9faade8a4625d575e0a4560e151a5e57267b78).

**Closed by dorkster** 2019-10-14 19:03 UTC
Labels: feature

**Comment by dorkster** [comment] 2019-10-14 19:07
Oh, and I also [updated the credits cutscene](https://github.com/flareteam/flare-engine/commit/2d648a07b4648c277fa2230db2a12c12fdce727d) to add you and a few other recent contributors to the list of programmers.

**Comment by m7600** [comment] 2019-10-14 19:26
Lol Justin (if I may), I don't feel like I deserve credit for a tiny, halfway-done contribution. You practically did all the work. But still, thanks! I'll try to write better stuff in the future. I'm still learning.

I hope the crash wasn't too severe. I'm kind of embarrassed that I submitted something that would cause a crash. But, if it makes you feel better, over here I had to deal with segmentation faults, core dumps, invalid pointers, and who knows what else. I know this doesn't sound very professional, but... I'm just being honest. No shame in being a newbie, I suppose.

**Comment by dorkster** [comment] 2019-10-14 19:34
Everyone starts somewhere! My first contribution to Flare was small as well, but I still got credited for it.

FYI: the crash/segfault I was getting was caused by [these lines](https://github.com/flareteam/flare-engine/commit/892e2bba042ace3eee5af33a8dfce54da2843a5b#diff-9ac12d9c27ffd5c0b99496db3cd4d963L351-L352). Noticed that both option widgets have an index of '2'.

**Comment by m7600** [comment] 2019-10-14 19:41
Ah crap, I see the problem. I'm such a knucklehead. I had actually fixed that last line over here by adding '3' to the last option, but I forgot to update the file when I made the PR. Good catch!
